# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

project_name: virtrun

version: 2

gomod:
  proxy: true

builds:
  - binary: virtrun
    mod_timestamp: "{{.CommitTimestamp}}"
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    formats: binary

release:
  header: |
    ## {{ .TagSubject }} ({{ .Now.Format "2006-01-02" }})
    {{ .TagBody }}

snapshot:
  version_template: "{{ .Tag }}"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

nfpms:
  - vendor: Virtrun
    homepage: https://github.com/aibor/virtrun
    maintainer: Tobias Böhm <code@aibor.de>
    description: Run commands in a minimal QEMU guest. Bring your own kernel.
    license: GPL-3.0-or-later
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: "asc"
  use: "github-native"
  filters:
    include:
      - "^feat"
      - "^fix"
