# SPDX-FileCopyrightText: 2025 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Test Reports

on:
  workflow_run:
    workflows: [ Test ]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test-report:
    name: Test report
    runs-on: ubuntu-latest
    steps:
    - name: Report test results
      uses: dorny/test-reporter@v2
      with:
        artifact: /test-results-(.+)/
        name: Test Report $1
        path: 'junit-report*.xml'
        reporter: java-junit

  coverage-report:
    name: Coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: go-coverage*
          github-token: "${{ github.token }}"
          run-id: "${{ github.event.workflow_run.id }}"

      - name: Report coverage for virtrun
        uses: 5monkeys/cobertura-action@master
        with:
          path: go-coverage/coverage.xml
          report_name: Coverage Report virtrun
          minimum_coverage: 75
          skip_covered: false

      - name: Report coverage for sysinit
        uses: 5monkeys/cobertura-action@master
        with:
          path: go-coverage-sysinit/coverage.xml
          report_name: Coverage Report sysinit
          minimum_coverage: 75
          skip_covered: false
